#!/bin/bash
# application_stop.sh
if [ -f /var/www/html/index.html ]; then
    echo "Backing up existing index.html"
    sudo mv /var/www/html/index.html /var/www/html/index.html.bak
fi

isExistApp = `pgrep apache2`
if [[ -n  $isExistApp ]]; then
    sudo service apache2 stop        
fi

